### DISCUSSION TITLE
[Request] 大神門能支持一下copilot-gpt4-service 嗎?

### DISCUSSION THREAD

**Discussion by hephaestus369** [lobehub/lobehub#1160] [General Question] [answered]
### 🥰 Feature Description

大神門能加入連接copilot-gpt4-service 嗎?

### 🧐 Proposed Solution

大神門能支持一下copilot-gpt4-service 嗎?
https://github.com/aaamoon/copilot-gpt4-service
localhost:8080
加個自訂API或地址localhost:8080 連接copilot-gpt4-service 或本地LLM
謝謝

[a comment by an automated account is not shown]

**Comment by arvinxx** [comment]
具体需要做什么事情

[a comment by an automated account is not shown]

**Comment by usefortemp** [comment]
使用copilot-gpt4-service会报错
{
  "endpoint": "http://copilot-gpt4-service:****/",
  "error": {
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-headers": "*",
      "access-control-allow-methods": "*",
      "access-control-allow-origin": "*",
      "content-length": "18",
      "content-type": "text/plain; charset=utf-8",
      "date": "***"
    },
    "stack": "Error: 405 Method Not Allowed\n    at W.generate (/app/.next/server/app/api/openai/chat/route.js:22:1855)\n    at tD.makeStatusError (/app/.next/server/app/api/openai/chat/route.js:22:13240)\n    at tD.makeRequest (/app/.next/server/app/api/openai/chat/route.js:22:13970)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async $ (/app/.next/server/app/api/openai/chat/route.js:2:2906)\n    at async /app/.next/server/app/api/openai/chat/route.js:7:64719\n    at async Y.execute (/app/.next/server/app/api/openai/chat/route.js:7:61612)\n    at async Y.handle (/app/.next/server/app/api/openai/chat/route.js:7:65986)\n    at async eC.handler (/app/.next/server/app/api/openai/chat/route.js:19:34582)\n    at async H (/app/.next/server/app/api/openai/chat/route.js:19:6577)",
    "status": 405
  }
}

**Comment by Hurray0** [comment]
本来就支持吧？设置好docker的环境变量就可以用了
具体是
OPENAI_PROXY_URL设为[url]/v1
OPENAI_API_KEY设为ghu_xxxxx

不过我目前使用插件还没有成功过？请问有人成功过吗，具体需要怎么弄呢？（我这边是提示开始绘图或者开始读取pdf，但是没有后续反应了）

[a comment by an automated account is not shown]

**Comment by pzcn** [comment]
本来就是支持的

[a comment by an automated account is not shown]

**Comment by Wxh16144** [comment, marked as answer]
2024/03/08 过来补充一下，我写了一个最小可用的 `docker-compose.yml` 配置，只需要准备 copilot 的 token 和 lobe-chat 的 access 即可。
https://github.com/Wxh16144/chat/blob/master/docker-compose.yml

```yml
version: "3.8"

services:
  copilot-gpt4-service:
    image: aaamoon/copilot-gpt4-service:latest
    container_name: copilot-gpt4-service
    restart: always
    ports:
      - "10100:8080"
    environment:
      - COPILOT_TOKEN=${GITHUB_COPILOT_PLUGIN_KEY}
      - SUPER_TOKEN=${LOBE_CHAT_ACCESS_CODE}
      - ENABLE_SUPER_TOKEN=true
      - RATE_LIMIT=200

  lobe-chat:
    depends_on:
      - copilot-gpt4-service
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - "10101:3210"
    environment:
      # If you don't choose hack
      # - HTTPS_PROXY=${LOBE_CLIENT_HTTP_PROXY}
      # - OPENAI_API_KEY=${LOBE_CHAT_OPENAI_TOKEN}
      # - OPENAI_PROXY_URL=${LOBE_CHAT_OPENAI_PROXY_URL}

      # hack github copilot to gpt4
      - OPENAI_API_KEY=${LOBE_CHAT_ACCESS_CODE}
      - OPENAI_PROXY_URL=http://copilot-gpt4-service:8080/v1
      - ACCESS_CODE=${LOBE_CHAT_ACCESS_CODE:-lobe66}
      - DEFAULT_AGENT_CONFIG=model=gpt-4;enableHistoryCount=true;historyCount=5;params.max_tokens=5000;
```

### 必须填写 `LOBE_CHAT_ACCESS_CODE`  和 `GITHUB_COPILOT_PLUGIN_KEY`
