### DISCUSSION TITLE
[Bug] cross origin request block

### DISCUSSION THREAD

**Discussion by BILAL324** [lobehub/lobehub#12096] [Self Hosting]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

cross origin request block even the request is 200 ok

even that link is accessible

![Screenshot from 2024-09-30 19-50-03](https://github.com/user-attachments/assets/c7d922c2-0230-477c-907f-c311a7f99caf)

[a comment by an automated account is not shown]

**Comment by dosubot** [comment]
To resolve the CORS error for a PUT request to your local server (`bilalbucke.localhost:9001`) in Docker on Ubuntu using Firefox, you need to ensure that the CORS headers are correctly configured on your server. Based on the provided `docker-compose.yml` file, it looks like you are using MinIO, which has CORS settings.

You need to configure the CORS settings for MinIO to allow requests from your local server. Here is how you can do it:

1. **Update the MinIO CORS configuration**: Ensure that the `MINIO_API_CORS_ALLOW_ORIGIN` environment variable is set correctly to allow requests from your local server. In your `docker-compose.yml`, it should look like this:

    ```yml
    minio:
      image: minio/minio
      container_name: lobe-minio
      network_mode: 'service:network-service'
      volumes:
        - './s3_data:/etc/minio/data'
      environment:
        - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
        - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
        - 'MINIO_API_CORS_ALLOW_ORIGIN=http://bilalbucke.localhost:9001'
      restart: always
      command: >
        server /etc/minio/data --address ":${MINIO_PORT}" --console-address ":9001"
    ```

2. **Set up CORS configuration in MinIO**: You need to create a CORS configuration file and apply it to your MinIO server. Here is an example of a CORS configuration JSON file (`cors.json`):

    ```json
    [
      {
        "AllowedOrigins": ["http://bilalbucke.localhost:9001"],
        "AllowedMethods": ["GET", "PUT", "POST", "DELETE"],
        "AllowedHeaders": ["*"],
        "ExposeHeaders": ["ETag"],
        "MaxAgeSeconds": 3000
      }
    ]
    ```

3. **Apply the CORS configuration**: Use the MinIO client (mc) to apply the CORS configuration to your MinIO server. First, install the MinIO client if you haven't already:

    ```sh
    wget https://dl.min.io/client/mc/release/linux-amd64/mc
    chmod +x mc
    sudo mv mc /usr/local/bin/
    ```

    Then, configure the MinIO client and apply the CORS settings:

    ```sh
    mc alias set myminio http://localhost:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
    mc admin config set myminio/ api.cors < cors.json
    ```

By ensuring that the CORS settings are correctly configured, you should be able to resolve the CORS error for your PUT request <sup>[[1]](https://github.com/lobehub/lobe-chat/blob/main/docker-compose/local/docker-compose.yml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
