### DISCUSSION TITLE
2024 Model Providers support | 2024 年模型服务商支持

### DISCUSSION THREAD

**Discussion by arvinxx** [lobehub/lobehub#1284] [General]
2025 support: 
- https://github.com/lobehub/lobe-chat/discussions/6157

----

LobeChat currently supports many model providers, and considering the development of the AI ecosystem, we have specifically opened this discussion to record everyone's needs for new model service providers. 

LobeChat 目前已经支持了诸多模型供应商，考虑到 AI 生态的发展，我们专门开放此贴用于记录大家对于新模型服务商的需求。

---

Currently, the service providers currently supported by LobeChat are as follows:

目前 LobeChat 已支持的服务商如下：

- [x] **OpenAI**
- [x] **Azure OpenAI** 
   - #177 
- [x] **AWS Bedrock** 
   - #1173
   - Claude3: #1551
- [x] **Google Model （Gemini Pro 、Gemini Pro Vision）**  
   - #1173
   - Gemini 1.5 pro: #1801
- [x] **Zhipu AI (智谱AI)**  
   - #1173
- [x] **Moonshot AI (月之暗面)**   by @arvinxx 
   - #1232
- [x] **Ollama (Local LLM)**  Thanks to @sjy 
   - #1265
- [x] **Perplexity AI** Thanks to @gijigae 
   - #1339
- [x] **Anthropic** Thanks to @danielglh 
  -  #1409
- [x] **Mistral** Thanks to @danielglh 
  - #1455
- [x] **Groq** Thanks to @jcdiv47  and @pzcn
  - #1562
  - #1570
  - #1569
- [x] **OpenRouter**: Thanks to @danielglh 
  - #1572
- [x] **01.AI（零一万物）**: Thanks to @MapleEve 
  - #1627
- [x] **TogetherAI**: Thanks to @phsontung
  - #1709 
- [x] **MiniMax** Thanks to @lwshen
  - #2087
- [x] **DeepSeek**:  Thanks to @RubuJam
  - #2446
  - #2484
- [x] **Qwen**:  Thanks to @justmywyw
  - #2715
- [x] **Stepfun(阶跃星辰)**： by @arvinxx 
  - #2803
- [x] **Baichuan (百川）**： Thanks to @hezhijie0327
  - #3097 
- [x] **Taichu(太初)**: Thanks to @hezhijie0327
  - #3129 
- [x] **360 AI（360智脑）** : Thanks to @hezhijie0327
  - #3130 
- [x] **Novita AI**: Thanks to @jasonhp
  - #3177 
- [x] **SiliconCloud**: Thanks to @sxjeru 
  - #3092 
- [x] **Fireworks AI** Thanks to  @hezhijie0327
  - #3392
- [x] **Spark (讯飞星火)**: Thanks to @hezhijie0327
  - #3098
- [x] **Github Models**: Thanks to @CloudPassenger 
  - #3869
- [x] **AI21 Labs**: Thanks to @hezhijie0327 
  - #3727
- [x] **Tencent Hunyuan(腾讯混元)**:  Thanks to @hezhijie0327 
  - #4147
- [x]  **Wenxin(文心一言)**:  by @arvinxx 
  - #2802
  - #4018
- [x] **Hugging Face Inference API**: by @arvinxx 
  - #4225 
-  [x] **SenseNova**: Thanks to @hezhijie0327 
  - #4162 
- [x] **Cloudflare AI**: Thanks to @BrandonStudio , @sxjeru 
  - #3402 
  - #2966
- [x] **xAI** : Thanks to @hezhijie0327 
  - #4627 
- [x] **InternLM**: Thanks to @hezhijie0327 
  - #4711
- [x] **Gitee AI**:   Thanks to @hezhijie0327 
  - #4716 

WIP：
- [ ] **Cohere** : Thanks to @ystoneman
  - #2539

Plan：

- [ ] replicate

> [!IMPORTANT]
>
> If you have any requests for new model suppliers, feel free to comment below. When the number of upvotes exceeds 15, we will consider implementing it.
>
> 如果大家对于新模型供应商有诉求，欢迎在下方跟帖，当up数超过 15 时，我们会考虑将其实现

---

### PRs Welcome 💞

- A demo PR of add OpenAI Compatible Provider: https://github.com/lobehub/lobe-chat/pull/4483

> [!TIP]
>
> We also welcome PRs. We have received many contributions regarding model Providers, so we have maintained a library of icons for LLMs and Provider vendors, facilitating everyone's future development. <https://github.com/lobehub/lobe-icons>
>
> 同时欢迎 PR，我们已经收获到许多关于模型 Provider 的贡献, 因此我们维护了一个 LLMs 和 Provider 供应商的图标库，方便大家后续开发 <https://github.com/lobehub/lobe-icons>

[![](https://github.com/lobehub/lobe-icons/assets/17870709/7e2c56d2-d7ea-4cb8-842b-22de162d6486)](https://github.com/lobehub/lobe-icons)

**Comment by gzxyls** [comment]
qwen

**Reply by arvinxx** [reply]
请具体说明一下？本地llm已经支持qwen

**Reply by heshunme** [reply]
大概指的是兼容阿里云作为模型提供商提供的一系列在线模型吧，https://help.aliyun.com/document_detail/2712809.html

**Reply by MapleEve** [reply]
是想要API模型还是红方那边制作的逆向API模型……逆向API模型的话已经是OpenAI规范了，自己部署之后就可以自己添加custom接入

**Comment by sammcj** [comment]
Auto populate from Ollama would be great.

**Reply by arvinxx** [reply]
It's a good idea

**Reply by ChristopherHaws** [reply]
A separate Ollama section would be nice. The only way I have been able to get this to work is by setting my localhost as the proxy for OpenAI which makes it so I can't use OpenAI at the same time.

**Reply by arvinxx** [reply]
@sammcj Now we have supported it!

<img width="1046" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/2c1b837c-904b-4edf-9377-24df6d4b2381">

**Reply by sammcj** [reply]
Nice! ❤️

**Comment by gijigae** [comment]
+1 for "[perplexity ai](https://docs.perplexity.ai/reference/post_chat_completions)". With their online models (pplx-70b-online and pplx-7b-online), users can directly search the internet without adding the SerpAPI plugin.

**Reply by arvinxx** [reply]
PR welcome~ 😆

**Reply by gijigae** [reply]
On it! Have already made necessary changes in a local branch and currently am using Perplexity Models. For the PR, only missing part is getting necessary icons for the model provider & models. I'm currently using Gemini icons 😇. To add additional icons, should I raise a separate PR in [the lobe-icons repository](https://github.com/lobehub/lobe-icons)?
![image](https://github.com/lobehub/lobe-chat/assets/81459/94b49b2f-59ce-42f0-aec0-8751a31a6b42)

**Reply by arvinxx** [reply]
actually we have  perplexity icon: https://icons.lobehub.com/components/perplexity

**Reply by gijigae** [reply]
Oh, found it and these icons are beautiful! I like this kind of aesthetic side of LobeChat as well. One question. Perplexity AI supports other models than their own such as Mixtral by Mistral and Codellama by Meta. Should I include them under Perplexity similarly to AWS Bedrock? I'm asking this question because if we are going to add Mistral as a model provider in the future, having the same model in multiple providers might confuse some users. Thought?
![image](https://github.com/lobehub/lobe-chat/assets/81459/d1ba7384-7f22-4826-be57-d5a868d5d47b)

**Reply by arvinxx** [reply]
It's OK, because different providers use different model-invoking implement. For example, you can't call aws's mixtral model with Perplexity AI' API Key.

**Reply by gijigae** [reply]
Noted. Will add Mixtral and Codellama along with other Perplexity models. Need to run a few tests since Perplexity AI requires additional logic such as FrequencyPenalty greater than 0. Will raise a PR once the test is done.

![image](https://github.com/lobehub/lobe-chat/assets/81459/f3f948e9-f0c1-4ee5-b2b9-d19fe9599996)

**Reply by gijigae** [reply]
@arvinxx have made necessary changes and just need to update locale related files. I noticed there is a CLI tool to automate LobeChat's translation workflow and I hope you could guide me through how I can leverage the tool as part of adding Perplexity AI's models. What will be the best course of actions to translate text for Perplexity AI's models? Added a few lines manually to the setting.json, but getting errors.

![image](https://github.com/lobehub/lobe-chat/assets/81459/bcb769f4-5235-47c7-b780-11b65eda6026)

**Reply by arvinxx** [reply]
## Step1: add Chinese default Locale:

add similar code here:

https://github.com/lobehub/lobe-chat/blob/fbcfc96a8df08f6ebfdb8b7b93add27a56695f7c/src/locales/default/setting.ts#L80-L87

like 

```js
    Perplexity: {
      title: 'Perplexity',
      token: {
        desc: '填入来自 Perplexity AI 的 API Key',
        placeholder: 'Perplexity AI API Key',
        title: 'API Key',
      },
    },
```

## Step2: run lobe-i18n

Automatically translate it:

```bash
npm run i18n
```
you can refer to https://github.com/lobehub/lobe-chat/wiki/Add-New-Locale#step-2-automatically-translate-language-files

**Reply by gijigae** [reply]
Oh, just submitted a PR, #1339 , before I saw Step2 😄.

**Reply by gijigae** [reply]
For the Step2, what are the steps required to add a few new lines to existing language files as in #1339 using lobe-i18n? Checked the document, but not sure how to add translation that is necessary for Perplexity models.

**Reply by arvinxx** [reply]
just run `npm run i18n`

**Reply by gijigae** [reply]
Ok, got it. i18n checks the diff and make necessary translation for other languages. Thanks for the update in PR!

![image](https://github.com/lobehub/lobe-chat/assets/81459/116be429-3559-46c1-bc6e-862eeaf0a05b)

**Comment by elonj** [comment]
If Claude API can be supported, that would be great.

**Reply by gijigae** [reply]
You can use Claude models via AWS Bedrock, which was implemented in #1173 .

**Reply by arvinxx** [reply]
I don't have access to claude , so I can't. If you can borrow me a claude API Key,  I'm glad to support the Claude.

**Reply by danielglh** [reply]
@arvinxx I can lend you a Claude API key. I will be glad to see Claude supported.

**Reply by danielglh** [reply]
Never mind, let me try to prepare a PR that adds Anthropic models support.

**Reply by danielglh** [reply]
@arvinxx here it is https://github.com/lobehub/lobe-chat/pull/1409

**Reply by arvinxx** [reply]
@elonj We have shipped it!

**Comment by sagarspatil** [comment]
Please add support for https://groq.com/

World’s Fastest Inference
Groq has demonstrated 18x faster LLM inference performance on Anyscale’s LLMPerf Leaderboard compared to top cloud-based providers.

**Reply by arvinxx** [reply]
**the upvote is more than 5, we will add Groq Soon.**

**Reply by arvinxx** [reply]
@sagarspatil we have supported Groq! https://github.com/lobehub/lobe-chat/pull/1569

**Comment by deanrie** [comment]
Maybe add openrouter.ai & together.ai?

**Reply by arvinxx** [reply]
I think  openrouter is a yes!

**Reply by danielglh** [reply]
Openrouter is great. However it may require some UI change because it just has too many models. It makes more sense for the user to select some of them instead of using all. Otherwise it will be a huge list.

**Reply by arvinxx** [reply]
you are right, there is a simmliar PR to achieve this: https://github.com/lobehub/lobe-chat/pull/1397

**Reply by arvinxx** [reply]
**the upvote is more than 5, we will add openrouter and together.ai Soon.**

**Reply by IvanMazh** [reply]
together.ai forgot to add to the list

**Reply by arvinxx** [reply]
We have support OpenRouter AI: https://github.com/lobehub/lobe-chat/pull/1572

**Reply by deanrie** [reply]
Thank you ❤️

**Reply by arvinxx** [reply]
We have supported TogtherAI thanks to @phsontung  ! #1709

**Comment by danielglh** [comment]
Mistral, Claude & OpenRouter

**Reply by danielglh** [reply]
- Anthropic PR here: https://github.com/lobehub/lobe-chat/pull/1409
- Mistral PR here: https://github.com/lobehub/lobe-chat/pull/1455

**Comment by johnwayne087** [comment]
Is Claude going to get support? (Anthropic)

**Reply by danielglh** [reply]
I'm working on a PR.

**Reply by ccdanpian** [reply]
Claude 3出来了，这个可以加一下aws bedrock里的3吗？

**Reply by arvinxx** [reply]
@ccdanpian 欢迎提 PR

**Reply by ccdanpian** [reply]
> @ccdanpian 欢迎提 PR

有心无力啊，这种规模的对我来说难度系数有点高:)😆

**Reply by arvinxx** [reply]
@ccdanpian aws provider 已经有了，加新模型只是加个 JSON 配置项而已，如下： https://github.com/lobehub/lobe-chat/blob/d5929f6093a3cb0ceebd4520bd7a29c2b63486f2/src/config/modelProviders/bedrock.ts#L13-L19

**Reply by ccdanpian** [reply]
👍  明天试试

**Comment by yichengvfx** [comment]
please add Groq model plz, this model speed is insane

**Comment by lesonky** [comment]
申请增加GCP的Vertex AI大模型服务，此类服务用服务账号身份认证。可以满足企业级数据合规要求。🙏

**Reply by arunkumarakvr** [reply]
@arvinxx So, what is the point of this here while there are already many users of Gemini 1 or PaLM 2 APIs everywhere for Google Cloud Vertex AI Studio particularly?

**Reply by arvinxx** [reply]
@arunkumarakvr Actually I don't know there are enough users but by now. Compare with other providers, Goole Vertex AI is actually not so popular. For example , the 01.AI get 9 upvote just in one week, the Groq get 15 upvotes util we add it. The Vertex AI just get 5 upvotes in 15 days. And that's the truth.

**Reply by arvinxx** [reply]
the upvote is more than 8, we will add Google Vertex AI Soon.

**Reply by AiharaMahiru** [reply]
There are still fewer API providers that offer the Claude family of models, I've used AWS before as a Claude API, but asking me to provide sensitive data such as credit card statements is unacceptable!

**Reply by ViktorJJF** [reply]
I would like Vertex AI in Lobechat too pleasee

**Comment by CXwudi** [comment]
[LiteLLM Proxy](https://docs.litellm.ai/docs/simple_proxy). It provides a unified OpenAI compatible API for [20+ different providers](https://docs.litellm.ai/docs/providers) both locally like Ollama or remotely like Huggingface/Bedrock/TogetherAI/etc.

A [sample LiteLLM Proxy config file](https://docs.litellm.ai/docs/proxy/configs#quick-start) looks like:
``` yml
model_list:
  - model_name: gpt-3.5-turbo ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: azure/gpt-turbo-small-eu ### MODEL NAME sent to `litellm.completion()` ###
      api_base: https://my-endpoint-europe-berri-992.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY_EU" # does os.getenv("AZURE_API_KEY_EU")
      rpm: 6      # [OPTIONAL] Rate limit for this deployment: in requests per minute (rpm)
  - model_name: bedrock-claude-v1 
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-turbo-small-ca
      api_base: https://my-endpoint-canada-berri992.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY_CA"
      rpm: 6
  - model_name: anthropic-claude
    litellm_params: 
      model="bedrock/anthropic.claude-instant-v1"
      ### [OPTIONAL] SET AWS REGION ###
      aws_region_name="us-east-1"
  - model_name: vllm-models
    litellm_params:
      model: openai/facebook/opt-125m # the `openai/` prefix tells litellm it's openai compatible
      api_base: http://0.0.0.0:8000
      rpm: 1440
    model_info: 
      version: 2

litellm_settings: # module level litellm settings - https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py
  drop_params: True
  set_verbose: True
  input_callback:
  - langfuse
  success_callback:
  - langfuse
  failure_callback:
  - langfuse
  add_function_to_prompt: True
general_settings: 
  master_key: sk-1234 # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)
```

Update: 
LiteLLM also comes with its own [user management system](https://docs.litellm.ai/docs/proxy/virtual_keys) where the maintainer of a litellm instance can create different virtual keys to share the proxy with friends
