### DISCUSSION TITLE
[HELP] Deploying Lobe-Chat with Server-Side Persistence and SSO | 部署带服务器端持久化和SSO的Lobe-Chat

### DISCUSSION THREAD

**Discussion by nikkoxgonzales** [lobehub/lobehub#2987] [Self Hosting] [answered]
Hello Lobe-Chat community,

I'm new to Lobe-Chat and trying to deploy it with server-side persistence and SSO. I'm encountering some issues and would appreciate your help.

Here's my current docker-compose.yml:

```yaml
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: *****
      POSTGRES_DB: lobedb
    ports:
      - "5432:5432"
    networks:
      - my_network

  lobechat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    environment:
      - ENABLE_OAUTH_SSO=1
      - NEXTAUTH_SECRET=*****
      - NEXT_AUTH_SSO_PROVIDERS=github
      - GITHUB_CLIENT_ID=*****
      - GITHUB_CLIENT_SECRET=*****
      - ACCESS_CODE=*****
      - NEXTAUTH_URL=https://*****/api/auth
      - ENABLE_FEATURES=webrtc_sync,edit_agent,dalle,check_updates
      - DATABASE_URL=postgres://user:*****@db:5432/lobedb
      - KEY_VAULTS_SECRET=*****
      - NEXT_PUBLIC_SERVICE_MODE=server
      - ANTHROPIC_API_KEY=*****
      - DEEPSEEK_API_KEY=*****
      - OPENAI_API_KEY=*****
    ports:
      - 3210:3210
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
```

I'm facing the following problems:

1. Server-side functionality doesn't work. What am I doing wrong?
2. I've confirmed that PostgreSQL is running and accessible.
3. The ACCESS_CODE doesn't appear to be functioning as expected. I can interact with chatbots once logged in via SSO, but I'm unsure how the access code should work.

My goal is to have a ChatGPT-like experience where chat history is synced across all devices for the same account, rather than being stored in the browser's cache.

Specific questions:
- Is my docker-compose configuration correct for server-side persistence?
- How should the ACCESS_CODE be implemented and used?
- Are there any additional steps or configurations needed to enable cross-device syncing?

Any guidance or suggestions would be greatly appreciated. Thank you!

-----------------------------------------------------------------

Lobe-Chat社区你们好，

我是Lobe-Chat的新用户，正在尝试部署带有服务器端持久化和SSO的版本。我遇到了一些问题，希望能得到你们的帮助。

以下是我当前的docker-compose.yml文件：

```yaml
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: *****
      POSTGRES_DB: lobedb
    ports:
      - "5432:5432"
    networks:
      - my_network

  lobechat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    environment:
      - ENABLE_OAUTH_SSO=1
      - NEXTAUTH_SECRET=*****
      - NEXT_AUTH_SSO_PROVIDERS=github
      - GITHUB_CLIENT_ID=*****
      - GITHUB_CLIENT_SECRET=*****
      - ACCESS_CODE=*****
      - NEXTAUTH_URL=https://*****/api/auth
      - ENABLE_FEATURES=webrtc_sync,edit_agent,dalle,check_updates
      - DATABASE_URL=postgres://user:*****@db:5432/lobedb
      - KEY_VAULTS_SECRET=*****
      - NEXT_PUBLIC_SERVICE_MODE=server
      - ANTHROPIC_API_KEY=*****
      - DEEPSEEK_API_KEY=*****
      - OPENAI_API_KEY=*****
    ports:
      - 3210:3210
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
```

我遇到了以下问题：

1. 服务器端功能似乎不工作。我哪里做错了吗？
2. 我已确认PostgreSQL正在运行且可访问。
3. ACCESS_CODE似乎没有按预期工作。我可以通过SSO登录后与聊天机器人交互，但我不确定访问码应该如何使用。

我的目标是实现类似ChatGPT的体验，即同一账户的聊天历史可以在所有设备上同步，而不是存储在浏览器的缓存中。

具体问题：
- 我的docker-compose配置对于服务器端持久化是否正确？
- ACCESS_CODE应该如何实现和使用？
- 是否需要其他步骤或配置来启用跨设备同步？

非常感谢任何指导或建议。谢谢！
