### DISCUSSION TITLE
Setting Up a WebRTC Signaling Server for Lobe Chat Data Sync

### DISCUSSION THREAD

**Discussion by noname-oni** [lobehub/lobehub#3192] [General]
This guide will walk you through the process of setting up a self-hosted WebRTC signaling server behind Traefik for Lobe Chat data synchronization. Special thanks to community members dazzle, arvinxu, and cy948 for their contributions to this guide and for making this sync option possible.

## Setting Up the WebRTC Signaling Server

1. Enable WebRTC sync Flag in your lobe chat container with `FEATURE_FLAGS: "+webrtc_sync"`  environment variable.

2. Clone the signaling server [repository](https://github.com/lobehub/y-webrtc-signaling) to your machine:
   ```shell
   git clone https://github.com/lobehub/y-webrtc-signaling.git
   ```
   Note: Remember this path as you'll need to point your Docker to use this folder.

3. Add a signaling service as a separate container:
   ```yaml
   version: '3'
   services:
     webrtc-signaling:
       image: node:16-alpine
       volumes:
         - /path/to/your/files/y-webrtc-signaling:/app
       working_dir: /app
       command: sh -c "npm install && node index.js"
       ports:
         - "4444:4444"
       restart: unless-stopped
   ```
   
   or inside your current `docker-compose.yml` here is my compose file: 
   ```yaml
   version: '3.8'

   services:
     lobe-chat:
       image: lobehub/lobe-chat
       restart: unless-stopped
       container_name: lobe-chat
       ports:
         - '3210:3210'
       environment:
         FEATURE_FLAGS: "+webrtc_sync" # Add this variable
         # Place your other environment variables here

     webrtc-signaling:
       image: node:16-alpine
       volumes:
         - /path/to/your/y-webrtc-signaling:/app
       working_dir: /app
       command: sh -c "npm install && node index.js"
       ports:
         - "4444:4444"
       restart: unless-stopped

     # Optional bonus: Watchtower for automatic updates
      # watchtower:
      #   image: containrrr/watchtower
      #   restart: unless-stopped
      #   container_name: lobe-chat-updater
      #   volumes:
      #     - /var/run/docker.sock:/var/run/docker.sock
      #   command: --interval 3600 --cleanup
      #   environment:
      #     - WATCHTOWER_CLEANUP=true
      #     - WATCHTOWER_INCLUDE_RESTARTING=true
      #     - WATCHTOWER_ROLLING_RESTARTING=true
    ```
   

3. Run your containers using `docker compose up -d` or your preferred method.

4. Verify the server is working by accessing `{server_ip}:4444` in your browser. You should see a confirmation message.

5. In the Lobe Chat UI, go to Sync settings and add your signaling server IP (e.g., `http://{server_ip}:4444`).

This setup should work if you're using Lobe Chat locally without TLS/HTTPS.

---

> [!NOTE]
> The following sections assume you're using Traefik as a reverse proxy and Cloudflare for DNS and certificate management.

## Setting Up DNS and Traefik

To prevent CORS errors when using Lobe Chat through HTTPS behind a reverse proxy, follow these additional steps:

1. Ensure your Lobe Chat server's container can reach the Signaling Server (you may ping it to verify).
   If using Cloudflare, set a new CNAME DNS record to point to the signaling server (e.g., `signaling-lobe` with target @).

2. Configure Traefik with the following dynamic configurations:

   ```yaml
   http:
     routers:
       lobe-https-router:
         entryPoints:
           - https
         rule: "Host(`lobe.{MY_DOMAIN}`)"
         service: lobe-svc
         tls:
           certResolver: cloudflare

       lobe-http-router:
         rule: "Host(`lobe.{MY_DOMAIN}`)"
         service: lobe-svc
         entryPoints:
           - http

       lobe-signaling-https-router:
         entryPoints:
           - https
         rule: "Host(`signaling-lobe.{MY_DOMAIN}`)"
         service: lobe-signaling
         tls:
           certResolver: cloudflare

       lobe-signaling-http-router:
         rule: "Host(`signaling-lobe.{MY_DOMAIN}`)"
         service: lobe-signaling
         entryPoints:
           - http

       lobe-websocket-router:
         entryPoints:
           - https
         rule: "Host(`signaling-lobe.{MY_DOMAIN}`) && Path(`/`)"
         service: lobe-signaling-ws
         tls:
           certResolver: cloudflare
         middlewares:
           - websocket-middleware
           - websocket-headers

     middlewares:
       websocket-middleware:
         headers:
           customRequestHeaders:
             X-Forwarded-Proto: "https"
             X-Forwarded-Port: "443"
           customResponseHeaders:
             Strict-Transport-Security: "max-age=31536000"

       websocket-headers:
         headers:
           customRequestHeaders:
             Connection: "Upgrade"
             Upgrade: "websocket"
           customResponseHeaders:
             Connection: "Upgrade"
             Upgrade: "websocket"

     services:
       lobe-svc:
         loadBalancer:
           servers:
             - url: "http://{LOCAL_SERVER_IP}:3210"
           passHostHeader: true

       lobe-signaling:
         loadBalancer:
           servers:
             - url: "http://{LOCAL_SERVER_IP}:4444"
           passHostHeader: true

       lobe-signaling-ws:
         loadBalancer:
           servers:
             - url: "ws://{LOCAL_SERVER_IP}:4444"
           passHostHeader: true
   ```
   
 > [!NOTE]
 > I'm using `https` and `http` entrypoins, in your setup it could be `websecure` & `insecure` or something else.
 > Also you need to replace addresses with your domains as well as change ports if yours are custom.

3. In Lobe Chat settings, add the signaling server URL: `https://signaling-lobe.{MY_DOMAIN}/ws`

This configuration allows you to sync your Lobe Chat even when you're not on the local network.
