### DISCUSSION TITLE
分享一组自用的数据库版本私有化docker-compose

### DISCUSSION THREAD

**Discussion by ZeroDeng01** [lobehub/lobehub#3625] [Self Hosting]
**文件内容供参考，具体NEXTAUTH和S3等配置参考官方手册中相关环境变量的配置和说明**

```yaml

version: '3.8'

services:
  lobehub-postgres:
    image: pgvector/pgvector:pg16
    container_name: lobehub-postgres
    environment:
      POSTGRES_PASSWORD: pg**my*password
    networks:
      - pg
    ports:
      - "5432:5432"
    volumes:
      - /lobehub/pg:/var/lib/postgresql/data
    restart: always

  lobehub:
    image: lobehub/lobe-chat-database:latest
    container_name: lobehub
    environment:
      #网站域名
      APP_URL: https://lobehub.domain.com:3210
      #数据库配置
      KEY_VAULTS_SECRET: 6c90037f2c65ader6e31a84df45ef242 #自己生32位随机字符串
      DATABASE_URL: postgres://postgres:pg**my*password@lobehub-postgres:5432/postgres
      # NEXT_AUTH 相关，可以使用 auth0、Azure AD、GitHub、Authentik、zitadel 等
      NEXT_AUTH_SECRET: 39040**************db96e250
      NEXT_AUTH_SSO_PROVIDERS: auth0
      NEXTAUTH_URL: https://lobehub.domain.com/api/auth
      AUTH0_CLIENT_ID: a8DnKXzs**********5jMexSyXH
      AUTH0_CLIENT_SECRET: 6wiEDiGzU******************9mHLcd0z
      AUTH0_ISSUER: https://xxxxxxxxxxxx.us.auth0.com
      #S3配置
      S3_ACCESS_KEY_ID: dac924a************fff5402771
      S3_SECRET_ACCESS_KEY: 35df3b88596f72ca7**************b6ad6469d1c7b7f
      S3_ENDPOINT: https://860a2*************06992884.r2.cloudflarestorage.com
      S3_BUCKET: nas-lobehub
      S3_PUBLIC_DOMAIN: https://s3-lobuhub.domain.net
      #以下可以加入其他环境变量配置，具体按照自己实际情况配置
      FEATURE_FLAGS: +welcome_suggest
      OPENAI_PROXY_URL: 
      ENABLED_OPENAI: 1
      ENABLED_OLLAMA: 0
      #以上可以加入其他环境变量配置
    networks:
      - pg
    ports:
      - "3210:3210"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: lobehub-watchtower
    environment:
      - TZ=Asia/Shanghai
      - HTTP_PROXY=http://xxxxxxxxxx:10809 # 如果你的服务器无法连接dockerhub可以增加代理
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 0 */1 * * *" lobehub
    networks:
      - pg
    restart: always

networks:
  pg:
    driver: bridge

```
