### DISCUSSION TITLE
logto登录提示HTTPS错误[Bug]

### DISCUSSION THREAD

**Discussion by H-TTTTT** [lobehub/lobehub#3812] [Self Hosting] [answered]
### 📦 Environment

Docker

### 📌 Version

1.15.18

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

配置logto后，点击登录
![image](https://github.com/user-attachments/assets/c80b2deb-0773-4a36-b662-3e356da0a793)
会提示这个错误
![image](https://github.com/user-attachments/assets/a20a0f66-5678-4a53-8bfd-9444aab56f4e)

本地nas部署
使用官网的方法
https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#%E5%BF%AB%E9%80%9F%E5%90%AF%E5%8A%A8

配置如下，针对这个问题尝试修改参数修改如下，还是还是没有办法

 ```
 logto:
    image: svhd/logto:1.15.0
    container_name: lobe-logto
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - TRUST_PROXY_HEADER=1
      - PORT=${LOGTO_PORT}
      - DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/logto
      - ENDPOINT=http://192.168.31.11:${LOGTO_PORT}
      - ADMIN_ENDPOINT=http://192.168.31.11:3002
      - DEV_MODE=true
      - INSECURE_COOKIE=true
      - OIDC_CSRF_COOKIE_INSECURE=true
      - OIDC_COOKIE_DOMAIN=192.168.31.11
      - DISABLE_CRYPTO_SUBTLE=true
      - OIDC_CODE_CHALLENGE_METHOD=plain
      - OIDC_CODE_CHALLENGE_DIGEST_ALGORITHM=none
      - PKCE_CHALLENGE_METHOD=plain
      - NO_HTTPS=true
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DISABLE_SIGNUP=false
      - UNSAFE_ENABLE_LOCAL_WEBAUTHN=true
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']
    networks:
      - lobe-network
```

请问这个如何解决

[a comment by an automated account is not shown]

**Comment by dosubot** [comment]
@H-TTTTT 你好！我是 [Dosu](https://dosu.dev)，一个可以帮助你解决问题、回答疑问并成为贡献者的机器人。我在这里帮助你，等待人类维护者的到来。


To resolve the `Crypto.subtle` unavailable in insecure contexts error when configuring Logto with Docker on a local NAS deployment, you need to ensure that your application is served over HTTPS. The `Crypto.subtle` API is only available in secure contexts (HTTPS).

Here are the steps to configure HTTPS for your local deployment:

1. **Generate SSL Certificates**: You can use tools like OpenSSL to generate self-signed certificates for local development.

    ```sh
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
    ```

2. **Configure Nginx for SSL**: Use Nginx as a reverse proxy to serve your application over HTTPS. Create an Nginx configuration file (`nginx.conf`) with the following content:

    ```nginx
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /path/to/server.crt;
        ssl_certificate_key /path/to/server.key;

        location / {
            proxy_pass http://localhost:3210;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
    ```

3. **Update Docker Compose**: Ensure your Docker Compose file includes the Nginx service and maps the necessary ports.

    ```yaml
    version: '3.8'

    services:
      nginx:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./server.crt:/etc/nginx/server.crt
          - ./server.key:/etc/nginx/server.key
        ports:
          - "443:443"
          - "80:80"
        depends_on:
          - lobe

      lobe:
        image: lobehub/lobe-chat-database
        environment:
          - 'APP_URL=https://localhost:443'
          # other environment variables
        # other configurations
    ```

4. **Restart Services**: Restart your Docker services to apply the changes.

    ```sh
    docker compose up -d
    ```

By serving your application over HTTPS, the `Crypto.subtle` API will be available, and the error should be resolved <sup>[[1]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/server-database/docker-compose.mdx)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
