### DISCUSSION TITLE
OpenAI is not accessible with `getaddrinfo`

### DISCUSSION THREAD

**Discussion by unitythemaker** [lobehub/lobehub#3828] [Self Hosting] [answered]
### 📦 Environment

Docker

### 📌 Version

v1.15.19

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

The LobeChat is unable to access the OpenAI API, despite the server having successful access. This issue appears to be isolated to the LobeChat application, as other AI models (e.g., Claude, Perplexity) are functioning correctly. The server can successfully access the OpenAI API. The nextjs Docker container itself can access the OpenAI API. LobeChat frontend displays an error as shown. I am using a [production docker-compose installation](https://lobehub.com/docs/self-hosting/server-database/docker-compose#deploying-to-production)

![image](https://github.com/user-attachments/assets/2604c936-3ca1-4f9e-8581-04ffac9fa73b)

```json
{
  "error": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "api.openai.com"
    }
  },
  "endpoint": "https://api.openai.com/v1",
  "provider": "openai"
}
```

I am able to access OpenAI from both VM and nextjs container:
![image](https://github.com/user-attachments/assets/c464e546-5384-4879-a265-df07e2d0bc8f)

### 📷 Recurrence Steps

1. Install LobeChat production.
2. Create and configure an OpenAI API key.
3. Attempt to use OpenAI-based features in LobeChat.

### 🚦 Expected Behavior

LobeChat should be able to communicate with the OpenAI API successfully, as the server and Docker container can.

[a comment by an automated account is not shown]

**Comment by dosubot** [comment]
Hey there, @unitythemaker! I'm here to help you with any bugs, questions, or contributions you have. Let's tackle this issue together!


I found some similar issues that might be relevant to your problem:

1. **[Bug] The openai agent parameters in the Docker startup method cannot be switched to the official API direct connection mode**: This issue was closed and last updated on August 07, 2024. You can check the details [here](https://github.com/lobehub/lobe-chat/issues/2569) <sup>[[1]](https://github.com/lobehub/lobe-chat/issues/2569)</sup>.

2. **[Bug] 显示ConnectTimeoutError，应该如何解决**: This issue was closed and last updated on July 10, 2024. It was referenced by another issue and suggested that the problem might be due to a slow first token. You can check the details [here](https://github.com/lobehub/lobe-chat/issues/1297) <sup>[[2]](https://github.com/lobehub/lobe-chat/issues/1297)</sup>.

3. **无法链接 openai 并且 timeout**: This issue was closed and last updated on May 25, 2024. The suggested solution was to use a third-party proxy website instead of the official OpenAI API key. You can check the details [here](https://github.com/lobehub/lobe-chat/issues/747) <sup>[[3]](https://github.com/lobehub/lobe-chat/issues/747)</sup>.

Regarding your specific issue, the `ENOTFOUND` error indicates a DNS resolution problem. Here are some steps you can take to troubleshoot and resolve this issue:

1. **Check DNS Configuration**: Ensure that the DNS settings in your Docker environment are correctly configured. The `network-service` container in the Docker Compose setup does not have specific DNS settings configured, so it relies on the default DNS settings of the host machine <sup>[[4]](https://github.com/lobehub/lobe-chat/blob/main/docker-compose/local/docker-compose.yml)</sup>.

2. **Verify `OPENAI_PROXY_URL`**: Make sure that the `OPENAI_PROXY_URL` environment variable is correctly set, including the proper `/v1` suffix if needed. An incorrect configuration can lead to connectivity issues <sup>[[5]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/faq/no-v1-suffix.zh-CN.mdx)</sup>.

3. **Debugging Tools**: Enable the `DEBUG_ZEROONE_CHAT_COMPLETION` environment variable by setting it to `1`. This will call the `debugStream` function and provide more detailed information about the API connectivity issues <sup>[[6]](https://github.com/lobehub/lobe-chat/blob/main/src/libs/agent-runtime/deepseek/index.test.ts)</sup>.

4. **Environment Variables**: Ensure that all required environment variables for configuring the OpenAI API in LobeChat are correctly set. This includes `OPENAI_API_KEY`, `OPENAI_PROXY_URL`, and others as needed <sup>[[7]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/environment-variables/model-provider.mdx)</sup>.

By following these steps, you should be able to identify and resolve the DNS resolution issue affecting your LobeChat's connectivity to the OpenAI API.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by unitythemaker** [comment]
I tried to manually add ``api.openai.com`` to **container's** ``/etc/hosts`` and it worked.
```bash
# Start a sh shell in container as root user
docker exec -u 0 -it lobe-database sh
# Open hosts file
vi /etc/hosts
# I added this line:
# 104.18.6.192 api.openai.com
```

Tried to check the connection again, it worked:
![image](https://github.com/user-attachments/assets/facb3e37-f015-4a42-a7f1-337aeacf04f3)

**Comment by arvinxx** [comment]
@hezhijie0327 is this same as before?

**Comment by unitythemaker** [comment]
I got the same error for ``api.deepseek.com`` too right now. Claude and Perplexity still works fine though.

**Comment by hezhijie0327** [comment]
@unitythemaker have a try to mapping host's `/etc/resolv.conf` to container
```
  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    network_mode: 'service:network-service'
    volumes:
      - '/etc/resolv.conf:/etc/resolv.conf'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      logto:
        condition: service_started

    environment:
      - 'APP_URL=http://localhost:3210'
      - 'NEXT_AUTH_SSO_PROVIDERS=logto'
      - 'KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ='
      - 'NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg'
      - 'NEXTAUTH_URL=http://localhost:${LOBE_PORT}/api/auth'
      - 'LOGTO_ISSUER=http://localhost:${LOGTO_PORT}/oidc'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_ENDPOINT=http://localhost:${MINIO_PORT}'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_PUBLIC_DOMAIN=http://localhost:${MINIO_PORT}'
      - 'S3_ENABLE_PATH_STYLE=1'
    env_file:
      - .env
    restart: always
```

**Comment by unitythemaker** [comment]
Umm, server uses systemd-resolved (Ubuntu 24), so that wouldn't work because host's resolv.conf looks like this, the nameserver is localhost:
```conf
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
search .
```

When I try nslookup with ``127.0.0.53``:
```
docker exec -u 0 -it lobe-database sh
/ # nslookup google.com
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.184.238
Name:	google.com
Address: 142.250.184.238
Name:	google.com
Address: 2a00:1450:4001:813::200e
Name:	google.com
Address: 2a00:1450:4001:813::200e

/ # nslookup google.com 127.0.0.53
;; communications error to 127.0.0.53#53: connection refused
;; communications error to 127.0.0.53#53: connection refused
;; communications error to 127.0.0.53#53: connection refused
;; no servers could be reached


/ #
```

However, I believe the issue is not about DNS configuration but also I am confused. Because, host can resolve it, container can resolve it, even the node can resolve it but for both deepseek and openai lobe app can't.

This is an image from container where I tried to fetch OpenAI API:
![image](https://github.com/user-attachments/assets/806da2bd-658e-4dae-9d88-ee0ce54180fb)



<details>
<summary>
I am not sure if that could be a problem but I've changed the docker-compose a little:
</summary>

```yaml
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}'  # MinIO API
      - '9001:9001'  # MinIO Console
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_DOMAIN=${MINIO_DOMAIN}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=${MINIO_API_CORS_ALLOW_ORIGIN}'
    restart: always
    command: >
      server /etc/minio/data --address ":${MINIO_PORT}" --console-address ":9001"
    networks:
      - lobe-network

  logto:
    image: svhd/logto
    container_name: lobe-logto
    ports:
      - '${LOGTO_PORT}:${LOGTO_PORT}' # Logto
      - '3002:3002'  # Logto Admin
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'PORT=${LOGTO_PORT}'
      - 'DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/logto'
      - 'ENDPOINT=${LOGTO_ENDPOINT}'
      - 'ADMIN_ENDPOINT=${LOGTO_ADMIN_ENDPOINT}'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']
    networks:
      - lobe-network


  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - '${LOBE_PORT}:3210' # LobeChat
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_started
      logto:
        condition: service_started
    env_file:
      - .env
    restart: always
    networks:
      - lobe-network

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
```
</details>
