### DISCUSSION TITLE
[Bug] lobe-chat-db使用compose线上部署，logto启动后自动退出（其他服务正常）

### DISCUSSION THREAD

**Discussion by aiqj** [lobehub/lobehub#4009] [Self Hosting] [answered]
### 📦 Environment

Docker

### 📌 Version

27.1.2

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

lobe-chat-db使用compose线上部署，logto启动后自动退出（其他服务正常）
注：几天之前同样的操作，没有任何问题。就最近两天出现的这种问题。
报错信息：
> cli
> logto db seed --swe

info Seeding skipped
npm notice
npm notice New patch version of npm available! 10.8.2 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice To update run: npm install -g npm@10.8.3
npm notice

> start
> cd packages/core && NODE_ENV=production node .

(node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
cache    warn No Redis client initialized, skipping
pre      error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.

 See https://docs.logto.io/docs/references/using-cli/database-alteration for reference.

index    error Error while initializing app:
index    error Error: Undeployed database alterations found.
    at checkAlterationState (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26444:9)
    at async Promise.all (index 0)
    at async checkPreconditions (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26408:3)
    at async Promise.all (index 3)
    at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:26480:3

[a comment by an automated account is not shown]

**Comment by dosubot** [comment]
Hey @Amandizz! I'm here to help you with any bugs, questions, or contributions you have. Let's work together to solve this issue.


To resolve the issue of `logto` automatically exiting after starting when using Docker Compose for `lobe-chat-db` deployment, you should ensure that the database schema migration is correctly executed. Follow these steps to forcibly remove the database container and restart:

```sh
docker compose down  # Stop services
sudo rm -rf ./data   # Remove mounted database data
docker compose up -d # Restart
```

Ensure that your `docker-compose.yml` file is correctly configured. Here is an example configuration for the `logto` service:

```yml
logto:
  image: svhd/logto
  container_name: lobe-logto
  network_mode: 'service:network-service'
  depends_on:
    postgresql:
      condition: service_healthy
  environment:
    - 'TRUST_PROXY_HEADER=1'
    - 'PORT=${LOGTO_PORT}'
    - 'DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/logto'
    - 'ENDPOINT=http://localhost:${LOGTO_PORT}'
    - 'ADMIN_ENDPOINT=http://localhost:3002'
  entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']
```

This configuration ensures that the `logto` service waits for the `postgresql` service to be healthy before starting and runs the necessary database seed commands before starting the application <sup>[[1]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/server-database/docker-compose.mdx)</sup><sup>[[2]](https://github.com/lobehub/lobe-chat/blob/main/docker-compose/local/docker-compose.yml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
