### DISCUSSION TITLE
请问现在鉴权已经可以迁移到casdoor了吗？

### DISCUSSION THREAD

**Discussion by BiFangKNT** [lobehub/lobehub#4051] [Self Hosting]
如题。不知道部署是否顺利，用过的朋友来聊聊吧~ #3942

**Comment by SpeedupMaster** [comment]
部署没问题，部署后可以正常使用了，昨天刚试过
docker compose添加casdoor
```
  casdoor:
    image: casbin/casdoor:latest
    container_name: lobe-casdoor
    ports:
      - 8000:8000
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
      - driverName=postgres
      - dataSourceName=postgres://postgres:b750e83ac80f7261513axxxxxxxxx@postgresql:5432/casdoor?sslmode=disable
    volumes:
      - ./files:/files
    entrypoint:
      - /bin/sh
      - -c
      - ./server --createDatabase=true
```
环境变量中添加下面这几个
```
NEXT_AUTH_SSO_PROVIDERS=casdoor
AUTH_CASDOOR_ID=
AUTH_CASDOOR_SECRET=
AUTH_CASDOOR_ISSUER=
CASDOOR_WEBHOOK_SECRET=
```
