### DISCUSSION TITLE
How to completely disable authentication in self-hosted

### DISCUSSION THREAD

**Discussion by lukaszraczylo** [lobehub/lobehub#4169] [Self Hosting] [answered]
Hi everyone, thanks for the great product - it's much lighter and more pleasant to work with than others available on the market. I have the following scenario and issue in one:

* Internal deployment on the home cluster
* The reverse proxy handles authentication
* I would like to enable server mode so both PostgreSQL database and S3 storage is used
* Whenever I do it - I'm getting the following error when accessing the files

```
Sorry, the server has rejected your request, possibly due to insufficient permissions or invalid authentication.
```

I do not want to use any authentication with lobeChat. It should be available for my family users without the need to log in to the app itself.

I have following environment variables set:

```
            - name: API_KEY_SELECT_MODEL
              value: "turn"

            # AI access points
            - name: ENABLED_OPENAI
              value: "true"

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lobe-ai-keys
                  key: openai_api_key

            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lobe-ai-keys
                  key: anthropic_api_key

            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lobe-ai-keys
                  key: google_api_key

            # Storage
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: lobe-qnap-access
                  key: endpoint

            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: lobe-qnap-access
                  key: access_key_id

            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: lobe-qnap-access
                  key: access_secret_key

            - name: S3_BUCKET
              value: "lobe-llm"

            - name: S3_ENABLE_PATH_STYLE
              value: "true"

            # Database
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobe-db-access
                  key: db_url

            - name: DATABASE_DRIVER
              value: node

            - name: NEXT_PUBLIC_SERVICE_MODE
              value: "server"

            - name: APP_URL
              value: http://127.0.0.1:3210

            - name: KEY_VAULTS_SECRET
              value: "+/WlvCyOWCeVFuW0mThinGjMu8boqdz0WM="
```
