### DISCUSSION TITLE
Docker container takes a long time to stop and exits with code 137

### DISCUSSION THREAD

**Discussion by ideless** [lobehub/lobehub#5005] [Self Hosting]
The docker container takes a long time (~10s) to stop, and it exits with code 137.

Here is my docker compose file
```yaml
services:
  chat:
    image: lobehub/lobe-chat
    container_name: chat
    ports:
      - "3210:3210"
    environment:
      OPENAI_API_KEY: xxx
```

Here is part of the output of `docker inspect`:
```json
"State": {
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 137,
  "Error": "",
  "StartedAt": "2024-12-13T08:25:02.067114351Z",
  "FinishedAt": "2024-12-13T08:25:18.19748616Z"
}
```

Any help would be appreciated!
