### DISCUSSION TITLE
[Bug] lobe-chat-db使用compose线上部署，logto启动后自动退出（其他服务正常）  #4009

### DISCUSSION THREAD

**Discussion by Silas-Xu** [lobehub/lobehub#5151] [Self Hosting] [answered]
### 📦 Environment

Docker

### 📌 Version

v1.36.33

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

这个bug本来在 #4009 中解决，解决方案是指定Logto的版本为1.19.0，然而当我将`lobe-chat-db`更新到最新的`v1.36.33`后，即使采用指定版本的Logto，仍然无法正常启动Logto，异常信息与 #4009 相同。
是需要做一些额外的改动吗，如果改用casdoor的方案替换logto，能在部署文档中提供一下详细步骤吗？（部署文档中的域名模式只提供了Logto的配置方式，希望能增加casdoor的方式🙏）

[a comment by an automated account is not shown]

**Comment by dosubot** [comment]
@Silas-Xu 你好！我是[Dosu](https://dosu.dev)，我是一个可以帮助你解决bug、回答问题，并成为贡献者的机器人。我会在等待人类维护者的时候帮助你。期待和你一起解决问题！🤖


To address the issue with Logto not starting after updating `lobe-chat-db` to version `v1.36.33`, you might consider switching to Casdoor as an authentication provider. Here are the detailed steps for configuring Casdoor in your lobe-chat deployment:

1. **Create a Casdoor Application:**
   - Access your Casdoor WebUI (default is `http://localhost:8000/`) using the default credentials (`admin` / `123`).
   - Go to `Identity` -> `Applications`.
   - Create a new application named `LobeChat` or modify the existing `built-in` application.
   - Set the following fields:
     - Name, Display Name: `LobeChat`
     - Redirect URLs:
       - Local Development: `http://localhost:3210/api/auth/callback/casdoor`
       - Local Network IP Deployment: `http://your_server_ip:3210/api/auth/callback/casdoor`
       - Public Network: `https://lobe.example.com/api/auth/callback/casdoor`
   - Optionally, set a Logo and Form CSS for a better user experience:
     - Logo: `https://lobehub.com/icon-192x192.png`
     - Form CSS:
       ```html
       <style>
         .login-panel {
           padding: 40px 70px 0 70px;
           border-radius: 10px;
           background-color: #ffffff;
           box-shadow: rgba(17, 12, 46, 0.15) 0px 48px 100px 0px;
         }
         .panel-logo {
           width: 64px;
         }
         .login-logo-box {
           margin-top: 20px;
         }
         #parent-area > main > div > div.login-content > div.login-panel > div.login-form > div > div > button {
           box-shadow: none !important;
           border-radius: 10px !important;
           transition-property: all;
           transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
           transition-duration: 150ms;
           border: 1px solid #eee !important;
         }
         @media (max-width: 640px) {
           .login-panel {
             padding: 40px 0 0 0;
             box-shadow: none;
           }
         }
       </style>
       ```
   - Copy the `Client ID` and `Client Secret`.

2. **Configure Environment Variables:**
   - Set the `Client ID` and `Client Secret` as `AUTH_CASDOOR_ID` and `AUTH_CASDOOR_SECRET` in your environment variables.
   - Configure `AUTH_CASDOOR_ISSUER` based on your environment:
     - Local Development: `http://localhost:8000/`
     - Local Network: `http://your_server_ip:8000/`
     - Public Network: `https://lobe-auth-api.example.com/`
   - Ensure these environment variables are set for LobeChat:
     - `NEXT_AUTH_SECRET`: Generate using `openssl rand -base64 32`.
     - `NEXT_AUTH_SSO_PROVIDERS`: Set to `casdoor`.
     - `AUTH_CASDOOR_ID`: The client ID from Casdoor.
     - `AUTH_CASDOOR_SECRET`: The client secret from Casdoor.
     - `AUTH_CASDOOR_ISSUER`: The OpenID Connect issuer.
     - `NEXTAUTH_URL`: The callback address for OAuth verification, e.g., `https://lobe.example.com/api/auth`.

These steps will help you configure Casdoor as an authentication provider for LobeChat <sup>[[1]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/auth/next-auth/casdoor.mdx)</sup><sup>[[2]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx)</sup><sup>[[3]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/server-database/docker-compose.mdx)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/83dd2c41-98c4-41ea-934f-540693a8e161?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/83dd2c41-98c4-41ea-934f-540693a8e161?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/83dd2c41-98c4-41ea-934f-540693a8e161?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/83dd2c41-98c4-41ea-934f-540693a8e161?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/83dd2c41-98c4-41ea-934f-540693a8e161?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/83dd2c41-98c4-41ea-934f-540693a8e161?feedback_type=other)</sup>

**Comment by arvinxx** [comment]
大概率跟 LobeChat 没关系，建议检查下 logto 的版本和配置

[a comment by an automated account is not shown]

**Comment by SpeedupMaster** [comment]
先退回之前的版本，看下能不能正常启动，然后进入logto容器手动更新数据库。

[a comment by an automated account is not shown]

**Comment by Silas-Xu** [comment]
logto版本用1.19.0和latest都没成功。
更新前：logto==1.19.0, lobe==1.36.22 可以启动成功
更新后：logto==1.19.0, lobe==1.36.33 无法启动成功
更新时没有对配置做任何更改。
（已暂时回退到更新前的版本了）

[a comment by an automated account is not shown]

**Comment by SpeedupMaster** [comment]
casdoor可以参考这个
```
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lobe
      - POSTGRES_PASSWORD=b750e83ac80f7261513axxxxxxxxx
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./s3_data:/etc/minio/data
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
      - MINIO_DOMAIN=
      - MINIO_API_CORS_ALLOW_ORIGIN=
    restart: always
    command: |
      server /etc/minio/data --address ":9000" --console-address ":9001"

  casdoor:
    image: casbin/casdoor:latest
    container_name: lobe-casdoor
    ports:
      - 8000:8000
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
      - driverName=postgres
      - dataSourceName=postgres://postgres:b750e83ac80f7261513axxxxxxxxx@postgresql:5432/casdoor?sslmode=disable
    volumes:
      - ./files:/files
    entrypoint:
      - /bin/sh
      - -c
      - ./server --createDatabase=true
      
  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - 3210:3210
    depends_on:
      - postgresql
      - minio
      - casdoor
    env_file:
      - .env
    restart: always
volumes:
  data:
    driver: local
  s3_data:
    driver: local
networks: {}
```
