### DISCUSSION TITLE
使用docker run和docker compose部署lobe，环境变量配置未生效

### DISCUSSION THREAD

**Discussion by hmzll** [lobehub/lobehub#5879] [Self Hosting]
### 需求
给局域网部署了一个ollama接入的deepseek，并用lobe作为ui界面，不管谁来访问每次都需要手动设置一下ollama连接地址和模型。并且如果浏览器清空了缓存又得重新设置一次。所以想直接让lobe默认就设置好了ollama的url以及模型。

### 存在问题
可是现在我用docker run和docker compose部署，给了环境变量后未生效。

### 使用的docker部署命令
```bash
docker run -d -p 3210:3210 -e  ENABLED_OPENAI=0 -e OLLAMA_PROXY_URL=http://192.168.1.116:11434 -e OLLAMA_MODEL_LIST=deepseek-r1:latest --name lobe-chat lobehub/lobe-chat
```

### 使用的docker compose命令
```yaml
version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      OLLAMA_PROXY_URL: http://192.168.1.116:11434
      DEFAULT_AGENT_CONFIG: "model=deepseek-r1:latest"
      OLLAMA_MODEL_LIST: deepseek-r1:latest
      ENABLED_OPENAI: 0
```

#### 诉求
找到原因，或者提供另外一个满足我之前需求的办法
