### DISCUSSION TITLE
为中断性变更引入显式冲突

### DISCUSSION THREAD

**Discussion by BrandonStudio** [lobehub/lobehub#6313] [Ideas]
### 问题
目前使用云服务部署的用户通常采用了 Fork + 自动同步的模式，自动同步上游更改。
这种模式下，当上游主分支引入了中断性变更时，例如某些不兼容的环境变量，用户将在不知情的情况下自动引入了这些变更，使得程序运行出错。

### 相关特性
自动同步使用 GitHub Actions 完成，该操作使用 `GITHUB_TOKEN` 对存储库进行写入操作。
`GITHUB_TOKEN` 的权限不能写入 `.github/workflows` 中的工作流文件。

## 设计
在 `.github/workflows` 中添加一个无效的工作流，记录所有中断性变更。
例如，示例文件可能是这样的：
```yaml
name: Breaking Changes

on:
  workflow_dispatch:

breaking_changes:
  - uri: https://github.com/lobehub/lobe-chat/pulls/9999
    name: <NameOfBreakingChange>
    description:
    affect_modules:
      - auth
    required_actions:
      - Add an environment variable
    references:
      - https://github.com/lobehub/lobe-chat/pulls/9999
      - https://github.com/lobehub/lobe-chat/discussions/9000
```

### 好处
1. 记录所有中断性变更信息，方便用户查阅。Release 信息中也可包括相关内容。
2. 自动同步在中断性变更后将会失败，除非用户手动同步 Fork。在看到此文件变动后用户将知晓出现了中断性变更，并能便捷地获知影响内容和所需操作。
3. 为中断性变更的 PR 强制引入冲突。所有包含中断性变更的 PR 都将本 PR 包含的变更附在此文件的最后，这样一来，如果同时有两个 PR 包含中断性变更，合并时必然产生冲突，作者将以此获知相关信息，避免了信息差造成的意外 Bug。
