### DISCUSSION TITLE
作者您好，一直卡在logto这里

### DISCUSSION THREAD

**Discussion by Pel0915** [lobehub/lobehub#6612] [Self Hosting]
报错代码
```
> cli
> logto db seed --swe
fatal Error: timeout expired
    at Timeout._onTimeout (/etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:106:28)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
npm notice
npm notice New major version of npm available! 10.8.2 -> 11.1.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.1.0
npm notice To update run: npm install -g npm@11.1.0
npm notice
```
代码如下
```
name: lobe-chat-database
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5435:5432'
    volumes:
      - './sqldata:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=d72c87d0f0333333f'  # 修改
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './miniodata:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=admin'  # 修改
      - 'MINIO_ROOT_PASSWORD=dbdb82b0907c9a'  # 修改
      - 'MINIO_DOMAIN=lobe-s3-api.example.com:9001'  # 修改
      - 'MINIO_API_CORS_ALLOW_ORIGIN=http://192.168.2.100:3210' # Your LobeChat's domain name.
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"


  logto:
    image: svhd/logto
    container_name: lobe-logto
    ports:
      - '3007:3001'
      - '3008:3002'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:dbd656907c9a@lobe-postgres:5432/logto'  # 修改
      - 'ENDPOINT=https://lobe-auth-api.example.com'  # 修改
      - 'ADMIN_ENDPOINT=https://lobe-auth-ui.example.com'  # 修改
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat-db
    ports:
      - '3210:3210'
    depends_on:
      - postgresql
      - minio
      - logto
    env_file:
      - .env
    restart: always

volumes:
  sqldata:
    driver: local
  miniodata:
    driver: local

networks:
  lobe-network:
    driver: bridge
```
部署环境：飞牛nas，域名解析在cloudflare上，后使用v6通过lucky进行申请域名，nginx反代，测试minlo服务可支持可跳转的，由于logto一直连接不上数据库，后续也就无法展开，也试过casdoor，部署完成后点击注册就报错404，我个人更倾向于casdoor，但没有好的教学模板，一直折腾不明白
