### DISCUSSION TITLE
更换隧道服务后，文件向量化失败

### DISCUSSION THREAD

**Discussion by MacKenia** [lobehub/lobehub#7138] [General Question] [answered]
由于无法忍受CF tunnel减速器的 debuff，更换成 frpc 的内网穿透，配置如下：

```toml
serverAddr = "hide"
serverPort = 8500
metadatas.id = "hide"
transport.heartbeatInterval = 120

[[proxies]]
name = "hide"
type = "https"
customDomains = ["lobe.domain.com"]
[proxies.plugin]
type = "https2http"
localAddr = "172.22.0.4:3210"
hostHeaderRewrite = "172.22.0.4"
crtPath = "/"
keyPath = "/"

[[proxies]]
name = "hide"
type = "https"
customDomains = ["lobe-s3-api.domain.com"]
[proxies.plugin]
type = "https2http"
localAddr = "172.22.0.3:9000"
hostHeaderRewrite = "172.22.0.3"
crtPath = "/"
keyPath = "/"
```

证书使用的 acme.sh 自动申请的证书。

起初文件上传都存在问题，于是我删除了 `hostHeaderRewrite` 选项，问题解决。

如今文件无法向量化，点击向量化lobe报错如下：

<img width="346" alt="image" src="https://github.com/user-attachments/assets/6206645b-d8ee-4fc1-8ebd-ddb276148944" />

```
[embeddingFileChunks] error: Error [TRPCClientError]: fetch failed
    at g.from (.next/server/chunks/3645.js:53:8869)
    at <unknown> (.next/server/chunks/3645.js:53:14992) {
  shape: undefined,
  data: undefined,
  meta: undefined,
  [cause]: TypeError: fetch failed
      at async U (.next/server/chunks/3645.js:53:13894)
      at async Object.fetch (.next/server/chunks/3645.js:53:14343) {
    [cause]: [Error: unable to verify the first certificate] {
      code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
    }
  }
}
```
