### DISCUSSION TITLE
智能搜索深度阅读crawl必须配置环境变量SEARCH1API_API_KEY嘛？

### DISCUSSION THREAD

**Discussion by everstu** [lobehub/lobehub#7162] [General]
我没有配置SEARCH1API_API_KEY，但是我配置了JINA_API_KEY结果报错了，报错信息：
```
[rewrite] /discover -> http://127.0.0.1:3210/zh-CN__0__light/discover
Error [NetworkConnectionError]: Network connection error
    at Object.naive (.next/server/app/(backend)/trpc/tools/[trpc]/route.js:165:185546)
    at async mL.crawl (.next/server/app/(backend)/trpc/tools/[trpc]/route.js:165:188807)
    at async results.concurrency (.next/server/app/(backend)/trpc/tools/[trpc]/route.js:165:190108)
    at async (.next/server/chunks/12331.js:1:2392)
Error: SEARCH1API_API_KEY environment variable is not set. Visit https://www.search1api.com to get free quota.
    at Object.search1api (.next/server/app/(backend)/trpc/tools/[trpc]/route.js:165:186190)
    at mL.crawl (.next/server/app/(backend)/trpc/tools/[trpc]/route.js:165:188818)
    at async results.concurrency (.next/server/app/(backend)/trpc/tools/[trpc]/route.js:165:190108)
    at async (.next/server/chunks/12331.js:1:2392)
```
我的环境变量配置见下方：
```
environment:
        BROWSERLESS_TOKEN: xxxx
        JINA_API_KEY: xxxxx
        ACCESS_CODE: xxxx
        OPENAI_PROXY_URL: xxxxxx
        OPENAI_API_KEY:xxxxxxx
        NEXT_PUBLIC_CLIENT_DB: pglite
        SEARXNG_URL: xxxxxxxx
        ENABLED_OLLAMA: 0
        UMAMI_WEBSITE_ID: xxxxx
        UMAMI_SCRIPT_URL: xxxx
```
