### DISCUSSION TITLE
想问一下我这个后台设置为啥和 lobechat 官方的不同

### DISCUSSION THREAD

**Discussion by iTofu** [lobehub/lobehub#7317] [Self Hosting] [answered]
<img width="301" alt="Xnip2025-04-06_18-54-26" src="https://github.com/user-attachments/assets/3bb2175e-dd6c-41ad-8fbf-12bb3e938c15" />
<img width="294" alt="Xnip2025-04-06_18-54-32" src="https://github.com/user-attachments/assets/61370951-56c2-43ab-8cff-be17819f7733" />

后者是官方的，展示的是 "AI服务商"，而我这里是 "语言模型"，右边页面也不太一样。

我是通过 docker 部署，是因为我没有配置身份验证吗？

**Comment by SpeedupMaster** [comment, marked as answer]
部署数据库版或者Pglite版的就是官方展示的这样。后面会全部变成 "AI服务商"

**Reply by iTofu** [reply]
但我部署的应该是数据库版？docker compose：

```yml
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: unless-stopped
    ports:
      - '3210:3210'
    environment:
      - TZ=${TZ}
      # - APP_URL=${APP_URL}
      # 通用变量
      - ACCESS_CODE=${ACCESS_CODE}
      # - PLUGIN_SETTINGS=${PLUGIN_SETTINGS}
      # 服务端数据库
      - DATABASE_URL=${DATABASE_URL}
      - KEY_VAULTS_SECRET=${KEY_VAULTS_SECRET}
      # 身份验证服务
      # - AUTH_URL=${AUTH_URL}
      # - NEXT_AUTH_SECRET=${NEXT_AUTH_SECRET}
      # - NEXT_AUTH_SSO_PROVIDERS=${NEXT_AUTH_SSO_PROVIDERS}
      # - AUTH_LOGTO_ID=${AUTH_LOGTO_ID}
      # - AUTH_LOGTO_SECRET=${AUTH_LOGTO_SECRET}
      # - AUTH_LOGTO_ISSUER=${AUTH_LOGTO_ISSUER}
      # - NEXTAUTH_URL=${NEXTAUTH_URL}
      # - LOGTO_WEBHOOK_SIGNING_KEY=${LOGTO_WEBHOOK_SIGNING_KEY}
      # S3 存储服务
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PUBLIC_DOMAIN=${S3_PUBLIC_DOMAIN}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENABLE_PATH_STYLE=${S3_ENABLE_PATH_STYLE}
      - S3_SET_ACL=${S3_SET_ACL}
      - LLM_VISION_IMAGE_USE_BASE64=${LLM_VISION_IMAGE_USE_BASE64}
      # 模型服务商
      # - SEARXNG_URL=${SEARXNG_URL}
      # Ollama
      - ENABLED_OLLAMA=${ENABLED_OLLAMA}
      # OpenAI
      # One API
      - ENABLED_OPENAI=${ENABLED_OPENAI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_PROXY_URL=${OPENAI_PROXY_URL}
      - OPENAI_MODEL_LIST=${OPENAI_MODEL_LIST}
      # xAI Grok
      - XAI_API_KEY=${XAI_API_KEY}
      - XAI_MODEL_LIST=${XAI_MODEL_LIST}
      # 火山引擎 / Volcengine
      - VOLCENGINE_API_KEY=${VOLCENGINE_API_KEY}
      - VOLCENGINE_MODEL_LIST=${VOLCENGINE_MODEL_LIST}
```
