### ISSUE TITLE
Using LM Studio with vision models not work

### ISSUE THREAD

**Issue by corysus** [lobehub/lobehub#7696]
### 📦 Platform

Self hosting Docker

### 📦 Deploymenet mode

client db (lobe-chat image)

### 📌 Version

1.84.0

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

I'm trying to use the Gemma3 model which supports vision, but for some reason I always get this error:

`Error requesting LM Studio service, please troubleshoot or retry based on the following information`

```
{
  "error": "'url' field must be a base64 encoded image.",
  "endpoint": "https://192.168.1.10:1234/v1",
  "provider": "lmstudio"
}
```

I try other similar apps (LibreChat, AnythingLLM ...) and desktop LLM clients, and everything works without problem.

**Comment by corysus** [comment]
Hmmm... I already have this inside docker-compose.yml:

```
  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
    ...

    environment:
     ...
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
```
